import { TileConfig, CardConfig, HouseType } from './types';

export const HOUSE_INFO: Record<HouseType, { name: string; color: string; token: string; motto: string }> = {
  Gryffindor: { name: 'Gryffindor', color: '#e02424', token: '🦁', motto: 'Dũng cảm & Táo bạo' },
  Slytherin: { name: 'Slytherin', color: '#059669', token: '🐍', motto: 'Tham vọng & Ma mãnh' },
  Ravenclaw: { name: 'Ravenclaw', color: '#2563eb', token: '🦅', motto: 'Trí tuệ & Tính toán' },
  Hufflepuff: { name: 'Hufflepuff', color: '#d97706', token: '🦡', motto: 'Kiên trì & Trung thực' },
  Auror: { name: 'Auror Order', color: '#8b5cf6', token: '⚡', motto: 'Công lý & Bảo hộ' },
  DeathEater: { name: 'Death Eater', color: '#475569', token: '💀', motto: 'Hắc ám & Sức mạnh' },
  OrderOfPhoenix: { name: 'Phoenix Order', color: '#f97316', token: '🔥', motto: 'Bất khuất & Tái sinh' },
  Ministry: { name: 'Ministry of Magic', color: '#0284c7', token: '🏛️', motto: 'Trật tự & Pháp luật' },
};

export const COLOR_GROUP_STYLES: Record<string, { bg: string; text: string; name: string }> = {
  BROWN: { bg: '#8b4513', text: '#ffffff', name: 'Hẻm Knockturn' },
  LIGHT_BLUE: { bg: '#38bdf8', text: '#0f172a', name: 'Hẻm Xéo' },
  PINK: { bg: '#ec4899', text: '#ffffff', name: 'Làng Hogsmeade' },
  ORANGE: { bg: '#f97316', text: '#ffffff', name: 'Thung Lũng Godric' },
  RED: { bg: '#ef4444', text: '#ffffff', name: 'Rừng Cấm' },
  YELLOW: { bg: '#eab308', text: '#0f172a', name: 'Khuôn Viên Hogwarts' },
  GREEN: { bg: '#10b981', text: '#ffffff', name: 'Bộ Pháp Thuật' },
  DARK_BLUE: { bg: '#3b82f6', text: '#ffffff', name: 'Đỉnh Cao Ma Thuật' },
  STATION: { bg: '#64748b', text: '#ffffff', name: 'Nhà Ga Phù Thủy' },
  UTILITY: { bg: '#06b6d4', text: '#0f172a', name: 'Dịch Vụ Phép Thuật' },
};

export const HOGWARTS_TILES: TileConfig[] = [
  {
    id: 'tile-0',
    index: 0,
    name: 'Ga 9¾ (Khởi Hành)',
    type: 'GO',
    description: 'Nhận 500 Galleons khi vượt qua hoặc dừng tại đây.',
    icon: '🚂',
  },
  {
    id: 'tile-1',
    index: 1,
    name: 'Borgin & Burkes',
    type: 'PROPERTY',
    colorGroup: 'BROWN',
    price: 200,
    baseRent: 10,
    rentTiers: [10, 40, 120, 360, 600, 900],
    houseCost: 150,
    mortgageValue: 100,
    icon: '💀',
  },
  {
    id: 'tile-2',
    index: 2,
    name: 'Hộp Độc Dược',
    type: 'POTIONS',
    description: 'Rút 1 thẻ Độc Dược bí ẩn từ hầm ngục Snape.',
    icon: '🧪',
  },
  {
    id: 'tile-3',
    index: 3,
    name: 'Quán Cái Vạc Lủng',
    type: 'PROPERTY',
    colorGroup: 'BROWN',
    price: 200,
    baseRent: 15,
    rentTiers: [15, 60, 180, 540, 900, 1400],
    houseCost: 150,
    mortgageValue: 100,
    icon: '🍲',
  },
  {
    id: 'tile-4',
    index: 4,
    name: 'Thuế Thẩm Định Pháp Thuật',
    type: 'TAX',
    price: 300,
    description: 'Nộp 300 Galleons vào quỹ phòng cứu tế.',
    icon: '⚖️',
  },
  {
    id: 'tile-5',
    index: 5,
    name: 'Tàu Tốc Hành Hogwarts',
    type: 'STATION',
    colorGroup: 'STATION',
    price: 600,
    baseRent: 75,
    rentTiers: [75, 150, 300, 600],
    mortgageValue: 300,
    icon: '🚆',
  },
  {
    id: 'tile-6',
    index: 6,
    name: 'Tiệm Cú Eeylops',
    type: 'PROPERTY',
    colorGroup: 'LIGHT_BLUE',
    price: 320,
    baseRent: 20,
    rentTiers: [20, 90, 270, 800, 1200, 1700],
    houseCost: 150,
    mortgageValue: 160,
    icon: '🦉',
  },
  {
    id: 'tile-7',
    index: 7,
    name: 'Hộp Bùa Chú',
    type: 'CHARMS',
    description: 'Rút 1 thẻ Bùa Chú từ lớp học của Thầy Flitwick.',
    icon: '✨',
  },
  {
    id: 'tile-8',
    index: 8,
    name: 'Hiệu Sách Flourish & Blotts',
    type: 'PROPERTY',
    colorGroup: 'LIGHT_BLUE',
    price: 320,
    baseRent: 20,
    rentTiers: [20, 90, 270, 800, 1200, 1700],
    houseCost: 150,
    mortgageValue: 160,
    icon: '📚',
  },
  {
    id: 'tile-9',
    index: 9,
    name: 'Tiệm Đũa Phép Ollivanders',
    type: 'PROPERTY',
    colorGroup: 'LIGHT_BLUE',
    price: 360,
    baseRent: 25,
    rentTiers: [25, 120, 300, 900, 1400, 1900],
    houseCost: 150,
    mortgageValue: 180,
    icon: '🪄',
  },
  {
    id: 'tile-10',
    index: 10,
    name: 'Nhà Tù Azkaban (Thăm Nuôi)',
    type: 'JAIL',
    description: 'Nơi giam giữ Giám ngục Azkaban. Bạn đang ở khu thăm nuôi.',
    icon: '⛓️',
  },
  {
    id: 'tile-11',
    index: 11,
    name: 'Quán Ba Cây Chổi',
    type: 'PROPERTY',
    colorGroup: 'PINK',
    price: 450,
    baseRent: 30,
    rentTiers: [30, 150, 450, 1350, 1900, 2400],
    houseCost: 300,
    mortgageValue: 225,
    icon: '🍺',
  },
  {
    id: 'tile-12',
    index: 12,
    name: 'Mạng Lưới Bột Floo',
    type: 'UTILITY',
    colorGroup: 'UTILITY',
    price: 500,
    baseRent: 12,
    mortgageValue: 250,
    description: 'Tiền thuê = Điểm xúc xắc x12 (hoặc x30 nếu sở hữu cả 2 dịch vụ).',
    icon: '🔥',
  },
  {
    id: 'tile-13',
    index: 13,
    name: 'Tiệm Kẹo Công Tước Mật',
    type: 'PROPERTY',
    colorGroup: 'PINK',
    price: 450,
    baseRent: 30,
    rentTiers: [30, 150, 450, 1350, 1900, 2400],
    houseCost: 300,
    mortgageValue: 225,
    icon: '🍬',
  },
  {
    id: 'tile-14',
    index: 14,
    name: 'Tiệm Giỡn Zonko',
    type: 'PROPERTY',
    colorGroup: 'PINK',
    price: 500,
    baseRent: 40,
    rentTiers: [40, 180, 540, 1500, 2100, 2800],
    houseCost: 300,
    mortgageValue: 250,
    icon: '🎪',
  },
  {
    id: 'tile-15',
    index: 15,
    name: 'Trạm Xe Buýt Hiệp Sĩ',
    type: 'STATION',
    colorGroup: 'STATION',
    price: 600,
    baseRent: 75,
    rentTiers: [75, 150, 300, 600],
    mortgageValue: 300,
    icon: '🚌',
  },
  {
    id: 'tile-16',
    index: 16,
    name: "Nghĩa Trang Godric's Hollow",
    type: 'PROPERTY',
    colorGroup: 'ORANGE',
    price: 550,
    baseRent: 45,
    rentTiers: [45, 220, 600, 1700, 2300, 3000],
    houseCost: 300,
    mortgageValue: 275,
    icon: '🏰',
  },
  {
    id: 'tile-17',
    index: 17,
    name: 'Hộp Độc Dược',
    type: 'POTIONS',
    description: 'Rút 1 thẻ Độc Dược bí ẩn từ hầm ngục Snape.',
    icon: '🧪',
  },
  {
    id: 'tile-18',
    index: 18,
    name: 'Nhà Gia Đình Potter',
    type: 'PROPERTY',
    colorGroup: 'ORANGE',
    price: 550,
    baseRent: 45,
    rentTiers: [45, 220, 600, 1700, 2300, 3000],
    houseCost: 300,
    mortgageValue: 275,
    icon: '🏡',
  },
  {
    id: 'tile-19',
    index: 19,
    name: 'Nhà Cụ Bathilda Bagshot',
    type: 'PROPERTY',
    colorGroup: 'ORANGE',
    price: 600,
    baseRent: 50,
    rentTiers: [50, 250, 700, 1900, 2500, 3200],
    houseCost: 300,
    mortgageValue: 300,
    icon: '📜',
  },
  {
    id: 'tile-20',
    index: 20,
    name: 'Phòng Yêu Cầu (Kho Báu)',
    type: 'FREE_PARKING',
    description: 'Nghỉ ngơi an toàn & nhận toàn bộ tiền phạt tích lũy trong ván.',
    icon: '🚪',
  },
  {
    id: 'tile-21',
    index: 21,
    name: 'Tổ Nhện Khổng Lồ Aragog',
    type: 'PROPERTY',
    colorGroup: 'RED',
    price: 700,
    baseRent: 55,
    rentTiers: [55, 280, 800, 2200, 2800, 3400],
    houseCost: 450,
    mortgageValue: 350,
    icon: '🕷️',
  },
  {
    id: 'tile-22',
    index: 22,
    name: 'Hộp Bùa Chú',
    type: 'CHARMS',
    description: 'Rút 1 thẻ Bùa Chú từ lớp học của Thầy Flitwick.',
    icon: '✨',
  },
  {
    id: 'tile-23',
    index: 23,
    name: 'Túp Lều Bác Hagrid',
    type: 'PROPERTY',
    colorGroup: 'RED',
    price: 700,
    baseRent: 55,
    rentTiers: [55, 280, 800, 2200, 2800, 3400],
    houseCost: 450,
    mortgageValue: 350,
    icon: '🛖',
  },
  {
    id: 'tile-24',
    index: 24,
    name: 'Cây Liễu Roi',
    type: 'PROPERTY',
    colorGroup: 'RED',
    price: 750,
    baseRent: 65,
    rentTiers: [65, 320, 900, 2400, 3000, 3600],
    houseCost: 450,
    mortgageValue: 375,
    icon: '🌳',
  },
  {
    id: 'tile-25',
    index: 25,
    name: 'Bến Cỗ Xe Vọng Mã',
    type: 'STATION',
    colorGroup: 'STATION',
    price: 600,
    baseRent: 75,
    rentTiers: [75, 150, 300, 600],
    mortgageValue: 300,
    icon: '🐎',
  },
  {
    id: 'tile-26',
    index: 26,
    name: 'Đại Sảnh Đường Hogwarts',
    type: 'PROPERTY',
    colorGroup: 'YELLOW',
    price: 800,
    baseRent: 70,
    rentTiers: [70, 350, 1000, 2500, 3100, 3700],
    houseCost: 450,
    mortgageValue: 400,
    icon: '🕯️',
  },
  {
    id: 'tile-27',
    index: 27,
    name: 'Tháp Thiên Văn',
    type: 'PROPERTY',
    colorGroup: 'YELLOW',
    price: 800,
    baseRent: 70,
    rentTiers: [70, 350, 1000, 2500, 3100, 3700],
    houseCost: 450,
    mortgageValue: 400,
    icon: '🔭',
  },
  {
    id: 'tile-28',
    index: 28,
    name: 'Hệ Thống Cú Bưu Điện',
    type: 'UTILITY',
    colorGroup: 'UTILITY',
    price: 500,
    baseRent: 12,
    mortgageValue: 250,
    description: 'Tiền thuê = Điểm xúc xắc x12 (hoặc x30 nếu sở hữu cả 2 dịch vụ).',
    icon: '✉️',
  },
  {
    id: 'tile-29',
    index: 29,
    name: 'Tháp Gryffindor',
    type: 'PROPERTY',
    colorGroup: 'YELLOW',
    price: 850,
    baseRent: 75,
    rentTiers: [75, 380, 1100, 2700, 3300, 3900],
    houseCost: 450,
    mortgageValue: 425,
    icon: '🦁',
  },
  {
    id: 'tile-30',
    index: 30,
    name: 'Áp Giải Đến Azkaban',
    type: 'GO_TO_JAIL',
    description: 'Bị Giám Ngục bắt giữ! Vào tù ngay lập tức, không qua Ga 9¾.',
    icon: '👮‍♂️',
  },
  {
    id: 'tile-31',
    index: 31,
    name: 'Phòng Bí Mật (Sở Ban Ngành)',
    type: 'PROPERTY',
    colorGroup: 'GREEN',
    price: 950,
    baseRent: 85,
    rentTiers: [85, 420, 1200, 2800, 3500, 4200],
    houseCost: 600,
    mortgageValue: 475,
    icon: '🔮',
  },
  {
    id: 'tile-32',
    index: 32,
    name: 'Phòng Xét Xử Số 10',
    type: 'PROPERTY',
    colorGroup: 'GREEN',
    price: 950,
    baseRent: 85,
    rentTiers: [85, 420, 1200, 2800, 3500, 4200],
    houseCost: 600,
    mortgageValue: 475,
    icon: '🧑‍⚖️',
  },
  {
    id: 'tile-33',
    index: 33,
    name: 'Hộp Độc Dược',
    type: 'POTIONS',
    description: 'Rút 1 thẻ Độc Dược bí ẩn từ hầm ngục Snape.',
    icon: '🧪',
  },
  {
    id: 'tile-34',
    index: 34,
    name: 'Sảnh Trung Tâm Bộ Pháp Thuật',
    type: 'PROPERTY',
    colorGroup: 'GREEN',
    price: 1000,
    baseRent: 90,
    rentTiers: [90, 480, 1400, 3200, 3800, 4500],
    houseCost: 600,
    mortgageValue: 500,
    icon: '🏛️',
  },
  {
    id: 'tile-35',
    index: 35,
    name: 'Ga Làng Hogsmeade',
    type: 'STATION',
    colorGroup: 'STATION',
    price: 600,
    baseRent: 75,
    rentTiers: [75, 150, 300, 600],
    mortgageValue: 300,
    icon: '🚉',
  },
  {
    id: 'tile-36',
    index: 36,
    name: 'Hộp Bùa Chú',
    type: 'CHARMS',
    description: 'Rút 1 thẻ Bùa Chú từ lớp học của Thầy Flitwick.',
    icon: '✨',
  },
  {
    id: 'tile-37',
    index: 37,
    name: 'Hầm 713 Ngân Hàng Gringotts',
    type: 'PROPERTY',
    colorGroup: 'DARK_BLUE',
    price: 1100,
    baseRent: 110,
    rentTiers: [110, 550, 1600, 3500, 4200, 5000],
    houseCost: 600,
    mortgageValue: 550,
    icon: '🪙',
  },
  {
    id: 'tile-38',
    index: 38,
    name: 'Thuế Bảo An Gringotts',
    type: 'TAX',
    price: 250,
    description: 'Nộp 250 Galleons phí bảo vệ rồng canh giữ hầm vàng.',
    icon: '🐉',
  },
  {
    id: 'tile-39',
    index: 39,
    name: 'Văn Phòng Cụ Dumbledore',
    type: 'PROPERTY',
    colorGroup: 'DARK_BLUE',
    price: 1250,
    baseRent: 150,
    rentTiers: [150, 650, 1900, 4500, 5500, 6500],
    houseCost: 600,
    mortgageValue: 625,
    icon: '👑',
  },
];

export const CHARMS_CARDS: CardConfig[] = [
  {
    id: 'c-1',
    title: 'Bùa Dịch Chuyển (Accio)',
    description: 'Lập tức tiến về phía trước tới Ga 9¾. Nhận 500 Galleons.',
    action: 'MOVE_TO',
    targetTileIndex: 0,
  },
  {
    id: 'c-2',
    title: 'Bùa Triệu Hồi Đũa Phép',
    description: 'Tiến tới Tiệm Đũa Phép Ollivanders. Nếu chưa ai mua, bạn có thể mua ngay.',
    action: 'MOVE_TO',
    targetTileIndex: 9,
  },
  {
    id: 'c-3',
    title: 'Học Bổng Pháp Sĩ Xuất Sắc',
    description: 'Bạn được Bộ Pháp Thuật trao giải thưởng nghiên cứu. Nhận 450 Galleons.',
    action: 'MONEY',
    amount: 450,
  },
  {
    id: 'c-4',
    title: 'Cứu Thoát Khỏi Azkaban',
    description: 'Thẻ này cho phép bạn rời khỏi Azkaban miễn phí bất cứ lúc nào.',
    action: 'GET_OUT_OF_JAIL',
  },
  {
    id: 'c-5',
    title: 'Tăng Tốc Bằng Chổi Nimbus 2000',
    description: 'Bay nhanh thêm 3 ô về phía trước.',
    action: 'MOVE',
    amount: 3,
  },
  {
    id: 'c-6',
    title: 'Vi Phạm Đạo Luật Bí Mật',
    description: 'Bị phát hiện dùng phép thuật trước mặt Muggle. Bị giải về Azkaban ngay!',
    action: 'JAIL',
  },
  {
    id: 'c-7',
    title: 'Trùng Tu Lâu Đài (Reparo)',
    description: 'Chi phí sửa chữa bất động sản: Nộp 75 Galleons mỗi Túp Lều, 300 Galleons mỗi Lâu Đài.',
    action: 'REPAIRS',
    amount: 75,
  },
  {
    id: 'c-8',
    title: 'Bắt Được Trái Snitch Vàng',
    description: 'Giành chiến thắng trận Quidditch kịch tính. Mỗi người chơi phải chúc mừng bạn 60 Galleons!',
    action: 'PAY_PLAYERS',
    amount: 60,
  },
];

export const POTIONS_CARDS: CardConfig[] = [
  {
    id: 'p-1',
    title: 'Thuốc Phúc Lạc Dược (Felix Felicis)',
    description: 'Vận may ngập tràn cả ngày! Bạn trúng cược đua chổi 600 Galleons.',
    action: 'MONEY',
    amount: 600,
  },
  {
    id: 'p-2',
    title: 'Bồi Thường Vạc Độc Dược Nổ',
    description: 'Lỡ tay làm nổ vạc trong hầm Thầy Snape. Đền bù 150 Galleons vào quỹ phòng cứu tế.',
    action: 'MONEY',
    amount: -150,
  },
  {
    id: 'p-3',
    title: 'Thuốc Đa Quả (Polyjuice)',
    description: 'Cải trang tiến thẳng tới Đại Sảnh Đường Hogwarts thưởng thức yến tiệc.',
    action: 'MOVE_TO',
    targetTileIndex: 26,
  },
  {
    id: 'p-4',
    title: 'Cứu Thoát Khỏi Azkaban',
    description: 'Bảo lãnh từ Hội Phượng Hoàng. Giữ thẻ này để rời khỏi Azkaban bất cứ lúc nào.',
    action: 'GET_OUT_OF_JAIL',
  },
  {
    id: 'p-5',
    title: 'Bán Dược Liệu Hiếm Cho Bệnh Viện Thánh Mungo',
    description: 'Thu hoạch cỏ thi và rễ asphodel được giá hời. Nhận 300 Galleons.',
    action: 'MONEY',
    amount: 300,
  },
  {
    id: 'p-6',
    title: 'Viện Phí Thánh Mungo',
    description: 'Bị mọc tai lừa do uống nhầm thuốc biến hình. Trả viện phí 150 Galleons.',
    action: 'MONEY',
    amount: -150,
  },
  {
    id: 'p-7',
    title: 'Bảo Dưỡng Vạc & Lò Luyện Kim',
    description: 'Chi phí bảo dưỡng định kỳ: Trả 120 Galleons mỗi Túp lều, 350 Galleons mỗi Lâu Đài.',
    action: 'REPAIRS',
    amount: 120,
  },
  {
    id: 'p-8',
    title: 'Bị Giám Ngục Bắt Gặp',
    description: 'Vào ngục Azkaban ngay lập tức, không qua Ga 9¾, không nhận 500 Galleons.',
    action: 'JAIL',
  },
];
